### PR TITLE
Make language-agnostic DocumentWalker

### PR DESCRIPTION
**Pull request by MarcinJuraszek**
Fixes https://github.com/CodeConnect/SourceBrowser/issues/65#issuecomment-68602618

- Make document walker language-agnostic
- Move language-specific stuff, like checking what type of token it is or how to get proper name/type for it to IWalkerUtils, which is really simple and should not require any changes when changing DocumentWalker in the future.

### CODE REVIEW

**Comment by MarcinJuraszek** [comment]
I don't know how to test your project, so I didn't. But it's mostly just moving stuff around, so I'm not too much concerned about breaking anything. IWalker interface declaration didn't change.

**Comment by AmadeusW** [comment]
:+1: It's very well written! It's great to see C# 6 code.

Does WalkerSelector specifiy which implementation of IWalkerUtils to use, and constructor of DocumentWalker is the one that actually creates an instance of IWalkerUtils via walkerUtilsFactoryMethod?

**Comment by MarcinJuraszek** [comment]
Yes, you're correct.That's because both `CSWalkerUtils` and `VBWalkerUtils` need back reference to `IWalker` to call `VisitToken`.

**Comment by JoshVarty** [comment]
Looks good to me. 

Thanks for your help @MarcinJuraszek

**Pull request merged**
